//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatenMeister.AddOns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_DM_Addons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_DM_Addons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatenMeister.AddOns.Localization_DM_Addons", typeof(Localization_DM_Addons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during opening of the new html page:
        ///
        ///.
        /// </summary>
        internal static string Exception_ProcessStart_Html {
            get {
                return ResourceManager.GetString("Exception_ProcessStart_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xlsx)|*.xlsx|All files|*.*.
        /// </summary>
        internal static string Filter_ExcelExport {
            get {
                return ResourceManager.GetString("Filter_ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html files (*.html)|*.html|All files|*.*.
        /// </summary>
        internal static string Filter_HtmlExport {
            get {
                return ResourceManager.GetString("Filter_HtmlExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Suite.
        /// </summary>
        internal static string Menu_ComplianceSuite {
            get {
                return ResourceManager.GetString("Menu_ComplianceSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel....
        /// </summary>
        internal static string Menu_ExcelExport {
            get {
                return ResourceManager.GetString("Menu_ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extent.
        /// </summary>
        internal static string Menu_Extent {
            get {
                return ResourceManager.GetString("Menu_Extent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Menu_Report {
            get {
                return ResourceManager.GetString("Menu_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Simple Report....
        /// </summary>
        internal static string Menu_SimpleReport {
            get {
                return ResourceManager.GetString("Menu_SimpleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Manager.
        /// </summary>
        internal static string Menu_TypeManager {
            get {
                return ResourceManager.GetString("Menu_TypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Menu_Views {
            get {
                return ResourceManager.GetString("Menu_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;
        ///      Export of DatenMeister
        ///    &lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      body {
        ///        font-family: Arial, Helvetica;
        ///      }
        ///      
        ///      table {
        ///        border-collapse: collapse;
        ///      }
        ///
        ///      td {
        ///        border: 1px solid black;
        ///        padding: 4px 10px 4px 10px;
        ///      }
        ///
        ///      th {
        ///        border: 1px solid black;
        ///        padding: 4px 10px 4px 10px;
        ///      }
        ///
        ///      br {
        ///        mso-data-placement:same-cell;
        ///      }
        ///      
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleReport_Template {
            get {
                return ResourceManager.GetString("SimpleReport_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
