//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurnSystems.WebServer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_WebServer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_WebServer() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurnSystems.WebServer.Localization_WebServer", typeof(Localization_WebServer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP-Prefix: {0} ähnelt.
        /// </summary>
        internal static string AddedPrefix {
            get {
                return ResourceManager.GetString("AddedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sessions are collected ähnelt.
        /// </summary>
        internal static string CollectingSessions {
            get {
                return ResourceManager.GetString("CollectingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
        ///       &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;BurnSystems Webserver&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;		
        ///			body
        ///			{
        ///				background-color: #00007F;
        ///				color: #FFFFFF;
        ///				margin: 20px;
        ///				font-family: &quot;Courier New&quot;, Courier, monospace
        ///			}
        ///		&lt;/style&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;@[=Model-&gt;title]&lt;/h1&gt;
        ///		&lt;p&gt;@[=Model-&gt;url]&lt;/p&gt;
        ///		&lt;p&gt;@[=Model-&gt;message]&lt;/p&gt;
        ///		@[IF:Mode [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception while listening: {0} ähnelt.
        /// </summary>
        internal static string ExceptionDuringListening {
            get {
                return ResourceManager.GetString("ExceptionDuringListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception during Webrequest &apos;{0}&apos;: {1} ähnelt.
        /// </summary>
        internal static string ExceptionDuringWebRequest {
            get {
                return ResourceManager.GetString("ExceptionDuringWebRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload of files is currently not supported ähnelt.
        /// </summary>
        internal static string FileUploadNotSupported {
            get {
                return ResourceManager.GetString("FileUploadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content already had been sent to server. A second sending is not allowed ähnelt.
        /// </summary>
        internal static string FinishedSending {
            get {
                return ResourceManager.GetString("FinishedSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An exception occured during start-up. Please check the following preconditions:
        ///- Application has privileged execution rights
        ///- The website is already reserved by another application/server
        ///
        ///The error: {0} ähnelt.
        /// </summary>
        internal static string HttpListenerException {
            get {
                return ResourceManager.GetString("HttpListenerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sent form was not recognized: &apos;multipart/form-data&apos; ähnelt.
        /// </summary>
        internal static string InvalidMultipart {
            get {
                return ResourceManager.GetString("InvalidMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail &apos;{0}&apos; has been sent to &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum length of request exceeded: {0} Bytes (allowed: {1} Bytes) ähnelt.
        /// </summary>
        internal static string MaximumPostLengthExceeded {
            get {
                return ResourceManager.GetString("MaximumPostLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Webserver had been started.  ähnelt.
        /// </summary>
        internal static string ServerAlreadyStarted {
            get {
                return ResourceManager.GetString("ServerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Webserver was not started. ähnelt.
        /// </summary>
        internal static string ServerNotStarted {
            get {
                return ResourceManager.GetString("ServerNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading of sessions ähnelt.
        /// </summary>
        internal static string SessionsLoading {
            get {
                return ResourceManager.GetString("SessionsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception occured during loading of sessions: {0} ähnelt.
        /// </summary>
        internal static string SessionsLoadingException {
            get {
                return ResourceManager.GetString("SessionsLoadingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storing of sessions ähnelt.
        /// </summary>
        internal static string SessionsStoring {
            get {
                return ResourceManager.GetString("SessionsStoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception occured during storing of sessions: {0} ähnelt.
        /// </summary>
        internal static string SessionsStoringException {
            get {
                return ResourceManager.GetString("SessionsStoringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail to &apos;{0}&apos; was not send due to inactivation of mailsender by configuration. ähnelt.
        /// </summary>
        internal static string SkippingMail {
            get {
                return ResourceManager.GetString("SkippingMail", resourceCulture);
            }
        }
    }
}
