//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatenMeister.WPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_DatenMeister_WPF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_DatenMeister_WPF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatenMeister.WPF.Localization_DatenMeister_WPF", typeof(Localization_DatenMeister_WPF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been saved.
        /// </summary>
        internal static string ChangeHasBeenSaved {
            get {
                return ResourceManager.GetString("ChangeHasBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes of extent may be lost. Shall closing of application continue?.
        /// </summary>
        internal static string ChangesMayBeLost {
            get {
                return ResourceManager.GetString("ChangesMayBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        internal static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml-Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string File_Filter {
            get {
                return ResourceManager.GetString("File_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Extents.
        /// </summary>
        internal static string Menu_ViewExtents {
            get {
                return ResourceManager.GetString("Menu_ViewExtents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No edit is possible, until the object is stored. .
        /// </summary>
        internal static string MultiReference_NoEditPossible {
            get {
                return ResourceManager.GetString("MultiReference_NoEditPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dialog specification has been found. Dialog cannot be shown. .
        /// </summary>
        internal static string NoItemDialogFound {
            get {
                return ResourceManager.GetString("NoItemDialogFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object has been selected. .
        /// </summary>
        internal static string NoObjectSelected {
            get {
                return ResourceManager.GetString("NoObjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file has been found on the given location. .
        /// </summary>
        internal static string Open_FileDoesNotExist {
            get {
                return ResourceManager.GetString("Open_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will get lost. Shall changes be stored before continuing?.
        /// </summary>
        internal static string QuestionSaveChanges {
            get {
                return ResourceManager.GetString("QuestionSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will get lost.
        /// </summary>
        internal static string QuestionSaveChangesTitle {
            get {
                return ResourceManager.GetString("QuestionSaveChangesTitle", resourceCulture);
            }
        }
    }
}
